# Generated by Django 2.2 on 2019-04-16 13:59

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0093_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='category-icons'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_image_alt',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
