# Generated by Django 2.2.4 on 2019-08-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityarea',
            name='ubigeo',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
