# Generated by Django 2.2 on 2019-04-22 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
        ('shipping', '0015_auto_20190305_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='world.City'),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='city_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='world.CityArea'),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='country_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='world.CountryArea'),
        ),
        migrations.AddField(
            model_name='shippingzone',
            name='national',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='type',
            field=models.CharField(choices=[('price', 'Price based shipping'), ('weight', 'Weight based shipping'), ('location', 'Location based shipping')], max_length=30),
        ),
    ]
