# Generated by Django 2.2 on 2019-04-14 01:16

import colorfield.fields
import django.core.validators
from django.db import migrations
import saleor.site.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0021_auto_20190326_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='dashboard_button_color',
            field=colorfield.fields.ColorField(blank=True, default='#00BCD4', max_length=18),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dashboard_header_color',
            field=colorfield.fields.ColorField(blank=True, default='#2784FF', max_length=18),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dashboard_header_text_color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', max_length=18),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dashboard_logo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to=saleor.site.models.site_settings_dashboard_logo_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='dashboard_subheader_color',
            field=colorfield.fields.ColorField(blank=True, default='#4796FC', max_length=18),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_accent_color',
            field=colorfield.fields.ColorField(blank=True, default='#2784FF', max_length=18),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_header_color',
            field=colorfield.fields.ColorField(blank=True, default='#2784FF', max_length=18),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_header_text_color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', max_length=18),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='store_logo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to=saleor.site.models.site_settings_store_logo_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
        ),
    ]
