# Generated by Django 2.2 on 2019-04-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0022_auto_20190413_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cash_payment_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_against_delivery_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
