# Generated by Django 2.2 on 2019-04-15 15:34

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0091_auto_20190402_0853'),
        ('widget', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='scenes')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('alt', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=False)),
                ('active_on', models.DateField(blank=True, null=True)),
                ('active_until', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
                'permissions': (('manage_scenes', 'Manage scenes.'),),
            },
        ),
        migrations.CreateModel(
            name='Spotlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('point_y', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='product.Product')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotlights', related_query_name='spotlight', to='widget.Scene')),
            ],
        ),
    ]
