# Generated by Django 2.2.2 on 2019-07-29 16:16

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0003_scene_spotlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('text', models.TextField()),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BenefitTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='widget.Benefit')),
            ],
            options={
                'unique_together': {('language_code', 'benefit')},
            },
        ),
    ]
