# Generated by Django 2.2.4 on 2019-08-20 19:25

from django.db import migrations, models
import django.db.models.deletion
import django_prices.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0029_address_location_type'),
        ('store', '0006_footeritem'),
        ('order', '0073_auto_20190820_1425'),
        ('checkout', '0020_checkout_billing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningBoxOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running_box_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('price', django_prices.models.MoneyField(currency='PEN', decimal_places=2, max_digits=12)),
                ('checkout', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runningbox_order', related_query_name='runningbox_order', to='checkout.Checkout')),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='account.Address')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runningbox_order', related_query_name='runningbox_order', to='order.Order')),
                ('origin_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.PhysicalStore')),
            ],
        ),
        migrations.CreateModel(
            name='RunningBoxDeliveryPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('store', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runningbox_delivery_permission', related_query_name='runningbox_delivery_permission', to='store.PhysicalStore')),
            ],
        ),
    ]
