# Generated by Django 2.2.4 on 2019-08-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runningbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runningboxdeliverypermission',
            old_name='enabled',
            new_name='runningbox_enabled',
        ),
    ]
