# Generated by Django 2.2 on 2019-04-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0017_auto_20190130_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_type',
            field=models.CharField(choices=[('door-shipping', 'Envío a domicilio'), ('store-shipping', 'Recojo en tienda')], default='door-shipping', max_length=15),
        ),
    ]
