# Generated by Django 2.2.1 on 2019-05-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0019_auto_20190410_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='billing_type',
            field=models.CharField(choices=[('ballot', 'Boleta'), ('facture', 'Factura')], default='ballot', max_length=15),
        ),
    ]
