# Generated by Django 2.2 on 2019-04-15 19:52

from django.db import migrations, models
import django.db.models.deletion
import saleor.account.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('account', '0026_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('is_main_store', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_stores', related_query_name='physical_store', to='account.Address')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_stores', related_query_name='physical_store', to='sites.Site')),
            ],
            options={
                'ordering': ('name',),
                'permissions': (('manage_physical_stores', 'Manage sliders.'),),
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', saleor.account.models.PossiblePhoneNumberField(blank=True, default='', max_length=128, region=None)),
                ('physical_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', related_query_name='phone', to='store.PhysicalStore')),
            ],
        ),
    ]
