# Generated by Django 2.2 on 2019-04-16 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0022_auto_20190413_2016'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'Youtube'), ('twitter', 'Twitter'), ('pinterest', 'Pinterest')], max_length=20)),
                ('link', models.URLField(max_length=256)),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', related_query_name='social_network', to='site.SiteSettings')),
            ],
            options={
                'unique_together': {('site_settings', 'provider')},
            },
        ),
    ]
