# Generated by Django 2.2 on 2019-04-17 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_specialpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalstore',
            name='address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='physical_stores', related_query_name='physical_store', to='account.Address'),
        ),
    ]
