# Generated by Django 2.2.4 on 2019-08-16 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0023_auto_20190420_1827'),
        ('menu', '0013_auto_20190529_1055'),
        ('store', '0005_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='menu.Menu')),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_items', to='site.SiteSettings')),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
    ]
