# Generated by Django 2.2 on 2019-04-13 21:33

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0091_auto_20190402_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=70, null=True, validators=[django.core.validators.MaxLengthValidator(70)])),
                ('seo_description', models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='brands')),
                ('color', colorfield.fields.ColorField(blank=True, default='#FFFFFF', max_length=18)),
                ('is_featured', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(blank=True, related_name='brands', related_query_name='brand', to='product.Product')),
            ],
            options={
                'ordering': ('slug',),
                'permissions': (('manage_brands', 'Manage brands.'),),
            },
        ),
        migrations.CreateModel(
            name='BrandTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=70, null=True, validators=[django.core.validators.MaxLengthValidator(70)])),
                ('seo_description', models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=64)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='brand.Brand')),
            ],
            options={
                'unique_together': {('language_code', 'brand')},
            },
        ),
    ]
