# Generated by Django 2.2.1 on 2019-06-06 14:23

from django.db import migrations, models
import django.db.models.deletion
import django_prices.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0028_newslettersubscription'),
        ('store', '0005_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlovoOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_price', django_prices.models.MoneyField(currency='PEN', decimal_places=2, max_digits=12)),
                ('price', django_prices.models.MoneyField(currency='PEN', decimal_places=2, max_digits=12)),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Address')),
                ('origin_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.PhysicalStore')),
            ],
        ),
        migrations.CreateModel(
            name='GlovoDeliveryPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('store', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glovo_delivery_permission', related_query_name='glovo_delivery_permission', to='store.PhysicalStore')),
            ],
        ),
    ]
