# Generated by Django 2.2.2 on 2019-06-14 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0070_drop_update_event_and_rename_events'),
        ('checkout', '0020_checkout_billing_type'),
        ('glovo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glovoorder',
            name='estimated_price',
        ),
        migrations.AddField(
            model_name='glovoorder',
            name='checkout',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.Checkout'),
        ),
        migrations.AddField(
            model_name='glovoorder',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='glovoorder',
            name='glovo_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='glovoorder',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Order'),
        ),
        migrations.AddField(
            model_name='glovoorder',
            name='schedule_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
