# Generated by Django 2.2.4 on 2019-08-20 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glovo', '0002_auto_20190614_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glovoorder',
            name='checkout',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glovo_order', related_query_name='glovo_order', to='checkout.Checkout'),
        ),
        migrations.AlterField(
            model_name='glovoorder',
            name='delivery_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='account.Address'),
        ),
        migrations.AlterField(
            model_name='glovoorder',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glovo_order', related_query_name='glovo_order', to='order.Order'),
        ),
        migrations.AlterField(
            model_name='glovoorder',
            name='origin_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glovo_orders', related_query_name='glovo_order', to='store.PhysicalStore'),
        ),
    ]
