# Generated by Django 2.2 on 2019-04-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0012_auto_20190329_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='show_countdown',
            field=models.BooleanField(default=False),
        ),
    ]
