# Generated by Django 2.2.2 on 2019-06-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0070_drop_update_event_and_rename_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_type',
            field=models.CharField(choices=[('ballot', 'Boleta'), ('facture', 'Factura')], default='ballot', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(choices=[('door-shipping', 'Envío a domicilio'), ('store-shipping', 'Recojo en tienda')], default='door-shipping', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='user_first_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='order',
            name='user_last_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
