# Generated by Django 2.2.2 on 2019-07-30 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0071_auto_20190614_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_proof', models.ImageField(upload_to='payment_proofs')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
    ]
