# Generated by Django 2.2 on 2019-04-17 07:07

from django.db import migrations
import saleor.geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='position',
            field=saleor.geoposition.fields.GeopositionField(blank=True, null=True, max_length=42),
        ),
    ]
