# Generated by Django 2.2.2 on 2019-07-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_newslettersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='location_type',
            field=models.CharField(blank=True, choices=[('home', 'Casa'), ('office', 'Oficina'), ('building', 'Edificio'), ('condominium', 'Condominio'), ('country-house', 'Quinta'), ('businesses', 'Negocio'), ('other', 'Otro')], max_length=256),
        ),
    ]
