# Generated by Django 2.2.4 on 2019-08-28 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_cityarea_ubigeo'),
        ('account', '0029_address_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city_area_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='world.CityArea'),
        ),
        migrations.AddField(
            model_name='address',
            name='city_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='world.City'),
        ),
        migrations.AddField(
            model_name='address',
            name='country_area_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='world.CountryArea'),
        ),
    ]
